# Generated by Django 5.0.6 on 2024-06-15 14:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('experiance', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
