# Generated by Django 5.0.6 on 2024-06-16 05:41

import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='timestapm',
            field=models.DateTimeField(default=employee.models.get_kolkata_time),
        ),
    ]
